# Generated by Django 4.2.6 on 2023-11-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_rename_title_post_document_rename_author_post_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='uname',
        ),
    ]
