# Generated by Django 4.2.7 on 2023-12-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_rename_user_post_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
