# Generated by Django 4.2.6 on 2023-11-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0002_profile_fname_profile_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lname',
        ),
    ]
