# Generated by Django 4.2.6 on 2023-11-07 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0003_remove_profile_fname_remove_profile_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('User', 'User'), ('Agent', 'Agent')], default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
